theme: jekyll-theme-slate
github:
  is_project_page: "false"
title: Virtual PhD Visit
description: Welcome to the Virtual Visit Day for the Department of Chemical Engineering at Northeastern University!
